### ISSUE TITLE
Something went wrong while creating task 'ASSEMBLY_REPORT:REPORT_DTOL' unique id

### ISSUE THREAD

**Issue by mahesh-panchal** [NBISweden/Earth-Biogenome-Project-pilot#103]
**Describe the bug**

DTOL process throws an exception

```
ERROR ~ Error executing process > 'ASSEMBLY_REPORT:REPORT_DTOL (1)'

Caused by:
  Something went wrong while creating task 'ASSEMBLY_REPORT:REPORT_DTOL' unique id -- Offending keys: [
 - type=java.util.UUID value=c51f0cff-5a44-4663-860a-a4014f0c65d7,
 - type=java.lang.String value=ASSEMBLY_REPORT:REPORT_DTOL,
 - type=java.lang.String value=def tol_table = [
        tolId: tol_search_json.species[0].tolIds[0].tolId,
        species: tol_search_json.species[0].scientificName,
        class: tol_search_json.species[0].taxaClass,
        order: tol_search_json.species[0].order
    ].collect { key, value -> "$key\t$value" }.join('\n')
file("$task.workDir/DToL.tsv").text = tol_table
,
 - type=java.lang.String value=tol_search_json,
 - type=org.apache.groovy.json.internal.LazyMap value=[totalNumSpecies:1, species:[[commonName:stone crayfish, currentHighestTolidNumber:10, family:Astacidae, genus:Austropotamobius, kingdom:Metazoa, order:Decapoda, phylum:Arthropoda, prefix:qmAusTorr, scientificName:Austropotamobius torrentium, taxaClass:Malacostraca, taxonomyId:94942, tolIds:[[specimen:[specimenId:ERGA_DS_382X_01_01], tolId:qmAusTorr1], [specimen:[specimenId:ERGA_DS_382X_01_02], tolId:qmAusTorr2], [specimen:[specimenId:ERGA_DS_382X_01_03], tolId:qmAusTorr3], [specimen:[specimenId:ERGA_DS_382X_02_01], tolId:qmAusTorr4], [specimen:[specimenId:ERGA_DS_382X_02_02], tolId:qmAusTorr5], [specimen:[specimenId:ERGA_DS_382X_02_03], tolId:qmAusTorr6], [specimen:[specimenId:ERGA_DS_382X_03_01], tolId:qmAusTorr7], [specimen:[specimenId:ERGA_DS_382X_03_02], tolId:qmAusTorr8], [specimen:[specimenId:ERGA_DS_382X_04_01], tolId:qmAusTorr9], [specimen:[specimenId:ERGA_DS_382X_04_02], tolId:qmAusTorr10]]]]],
 - type=java.lang.String value=$,
 - type=java.lang.Boolean value=true]


```

The log shows the error is eventually caused by a NullPointerException:
```nextflow
Caused by: java.lang.NullPointerException: Cannot load from object array because "this.keys" is null
        at org.apache.groovy.json.internal.LazyMap.buildIfNeeded(LazyMap.java:134)
        at org.apache.groovy.json.internal.LazyMap.values(LazyMap.java:170)
        at nextflow.util.CacheHelper.hasher(CacheHelper.java:173)
        at nextflow.util.CacheHelper.hasher(CacheHelper.java:190)
        at nextflow.util.CacheHelper.hasher(CacheHelper.java:123)
        at nextflow.util.CacheHelper.hasher(CacheHelper.java:119)
        at nextflow.util.CacheHelper$hasher.call(Unknown Source)
        at nextflow.processor.TaskProcessor.computeHash(TaskProcessor.groovy:2168)
        ... 15 common frames omitted
```

**To Reproduce**

No idea how to reproduce.

**Expected behavior**

Task is created and doesn't error

**Version**

Nextflow version: 23.10.1

**Comment by mahesh-panchal** [comment]
Solution is to simply rerun.
